version: '3'
services:
  discord_bot:
    container_name: discord_bot
    build:
      context: ./discord_bot
    volumes:
      - input-volume:/usr/app/attachments
      - output-volume:/usr/app/output_results

  parser:
    container_name: parser
    build:
      context: ./parser
    volumes:
      - input-volume:/usr/app/attachments
      - output-volume:/usr/app/output_results

volumes:
  # keeping input and output data vols seperated 
  input-volume: 
  output-volume:

