version: '3'
services:
  discord_bot:
    container_name: bot
    build: ./d_bot_src
    volumes:
      - extraction_input:/usr/app/attachments
      - extraction_output:/usr/app/output_results

  parser:
    container_name: parser
    build: ./parser_src
    depends_on:
      - discord_bot
    volumes:
      - extraction_input:/usr/app/attachments
      - extraction_output:/usr/app/output_results

  broker:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
      - mosquitto_data:/mosquitto/data

    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host

volumes:
  extraction_input: 
    name: "input_ex"

  extraction_output:
    name: "output_ex"
  
  mosquitto_config:
    name: "config_mqtt"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./broker_src/config

  mosquitto_log:
    name: "log_mqtt"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./broker_src/log

  mosquitto_data:
    name: "data_mqtt"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./broker_src/data
